### PR TITLE
Create : Calendar Page And Button Responsive

### PR DESCRIPTION
**Pull request by Kali-Decoder**
Issue: 37

#### Short description of what this resolves:
Implement Calendar Button And A Calendar Page By Ant Design Npm Package and Tailwind Css.
#### Changes proposed in this pull request and/or Screenshots of changes:

-Mobile View 
mobile-view

-Web- View
web-view

-Calendar View
CalendarView

### CODE REVIEW

**Comment by atharva-gadekar** [comment]
### @Kali-Decoder, here are the changes I want :
<hr>
<ul>
<li> Place the calendar icon on the bottom right.
<li> Pull the recent changes and resolve merge conflicts.<ul/>

**Comment by Kali-Decoder** [comment]
@atharva-gadekar  bhaiya take a look i resolved conflicts and change button position to right-bottom

**Comment by atharva-gadekar** [comment]
@Kali-Decoder 
- Don't create a new route for the calendar. It should be like a pop-up. 
- On the Desktop, I want the calendar to cover only 30-40% of the width, like the calendar widget on Windows 11. Refer to the below image
- Once the calendar pop-up is open, clicking on the empty region outside the pop-up must close it.

image

**Comment by Kali-Decoder** [comment]
Okk i will create so how many points you are increasing because it is long task

**Comment by atharva-gadekar** [comment]
> Okk i will create so how many points you are increasing because it is long task

I have already increased the issue points to 30.

**Comment by Kali-Decoder** [comment]
@atharva-gadekar Done Bhaiya 
calnew

**Comment by atharva-gadekar** [comment]
@Kali-Decoder, Great Work! Just some final changes before I merge this.
- The calendar widget get closed even if I click on any date or try to change the year/month. Make it such that the widget doesn't close if one clicks inside the widget. It should only close if one clicks outside that region.
- The widget opens in the middle right. I want it to open in the bottom right, just above the calendar button.

**Comment by Kali-Decoder** [comment]
Ok Bhaiya

**Comment by Kali-Decoder** [comment]
Check Now

**Comment by atharva-gadekar** [comment]
Umm, I guess I wasn't able to convey things properly. When are you free for VC tonight or tomorrow? @Kali-Decoder

**Comment by Kali-Decoder** [comment]
Give me partials points bhaiya @atharva-gadekar

**Comment by Kali-Decoder** [comment]
@atharva-gadekar can we connect

**Pull request merged**
