### PR TITLE
Date added

### PR DESCRIPTION
**Pull request by vishalola**
Issue: 17

Date added as per the requirement

### CODE REVIEW

**Comment by vishalola** [comment]
@atharva-gadekar

**Comment by atharva-gadekar** [comment]
Will review it soon

**Comment by atharva-gadekar** [comment]
@vishalola I have reviewed it, I want you to make one small change, decrease the font size of the date after the `md` breakpoint. Decrease it further after the `sm` breakpoint. Make sure that there is enough spacing between the date and time after you decrease its size.

PS :
> `md:text-red-500` will make the text red for all values of width less than `768px`

**Comment by atharva-gadekar** [comment]
@vishalola Updates?

**Comment by vishalola** [comment]
@atharva-gadekar Sorry I was not keeping well. I'll make another PR soon.

**Pull request closed without merging**
