### PR TITLE
Adding Header 

### PR DESCRIPTION
**Pull request by Kali-Decoder**
Issue: 44

#### Short description of what this resolves:
Adding Header to Dashboard 
#### Changes proposed in this pull request and/or Screenshots of changes:
search1
search2

-
-
-

### CODE REVIEW

**Comment by atharva-gadekar** [comment]
Hello @Kali-Decoder, this issue requires you to implement the search functionality. The projects to be searched from will be available in the sidebar, which is under development. Kindly wait till its PR is merged and then implement a search feature.

##Changes Required 
1. Change the darkMode in `tailwind.config.js` to `darkMode: "class"` so that we will be able to manually trigger the dark mode in the future.
2. Decrease the size of the search icon. Take reference from the design. Try to follow the design rigorously.
3. Upon Clicking on the date. The calendar pop-up must appear just below the date. Currently it appears in the right middle of the screen. Fix this.
4. Remove the hyperlink in the `Welcome back, Neeraj Choubisa`.
5. You must implement a search feature just like the one in [Tailwind Docs](https://tailwindcss.com/docs/installation). On clicking search, a pop-up must open and there must be a dropdown just like when you search for something in the Tailwind Documentation.
6. Lastly, wait for the Sidebar PR to be merged and then implement the search functionality.

**Comment by atharva-gadekar** [comment]
@Kali-Decoder Updates?

**Comment by Kali-Decoder** [comment]
Implementing bhaiya

**Comment by atharva-gadekar** [comment]
@Kali-Decoder The sidebar is ready now! You can now complete this issue. Implement the changes which I have asked you in the previous msg.

**Comment by atharva-gadekar** [comment]
@Kali-Decoder Make the required changes by tomorrow

**Comment by atharva-gadekar** [comment]
@Kali-Decoder Updates?

**Comment by Kali-Decoder** [comment]
Bhaiya partial marking krdo me yeh issue nhi kr paunga abhi @atharva-gadekar

**Comment by atharva-gadekar** [comment]
Acha dekhta hu mai ruko

**Pull request closed without merging**
