### PR TITLE
Add quotes component

### PR DESCRIPTION
**Pull request by Im-Madhur-Gupta**
Issue: #23

#### Package(s) added:
- [react-loader-spinner](https://mhnpd.github.io/react-loader-spinner/docs/intro)

#### Changes proposed in this pull request and/or Screenshots of changes:

- Adds random quotes on the homepage which are fetched every 5 mins.
- Public API used for quotes: https://github.com/lukePeavey/quotable
- Quotes have fade-in & fade-out animation while they change.
- Adds loading spinner during quote fetching.

#### Screenshot:
Screenshot 2022-12-23 at 12 27 51 AM

### CODE REVIEW

**Comment by Im-Madhur-Gupta** [comment]
Hey @atharva-gadekar, lmk if any changes are required in the PR. Cheers.

**Comment by atharva-gadekar** [comment]
Hey @Im-Madhur-Gupta Great Work! Please check out the changes I have suggested on the Discord Channel. I will merge the PR soon after you make those changes. Take your time.

**Comment by Im-Madhur-Gupta** [comment]
@atharva-gadekar please check your Discord DMs once, thanks.

**Comment by Im-Madhur-Gupta** [comment]
@atharva-gadekar I have added the necessary fixes.

**Pull request merged**
